### ISSUE TITLE
Question: Are we still using the jira.users ?

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop-bot/snowdrop-bot#164]
## Question

Why do we have to configure the `jira.users` ? What is the purpose of that field ? Do we still need it ?

```
kubectl create secret generic snowdrop-jira \
    --from-literal=jira.username=<your jira username> \
    --from-literal=jira.password=<your jira password \
    --from-literal=jira.users=<the jira users>
```

**Comment by jacobdotcosta** [comment]
They are used in a process to gather JIRA issues and add also have them indexed on the bot. That functionality was never rolled-out but the code is there that's why we always have to pass the JIRA information, user, pw, url and associate list.

If we aren't going to use that in the short term, or not at all, we might want to at least remove the `ConfigProperty` annotations so those parameters  aren't required.
